--- #EC2 Instance Snapshot
- hosts: "{{ var_hosts }}"
  remote_user: "{{ var_remote_user }}"
  become: "{{ var_become }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  vars_files:
   - files/vars_local.yml
   - files/awscreds.yml
  tasks:
   -  name: Taking the snapshot of the an instance
      ec2_snapshot:
       aws_access_key: "{{ aws_id }}"
       aws_secret_key: "{{ aws_key }}"
       region: "{{ aws_region }}"
       instance_id: "{{ instance_id }}"
       device_name: "{{ var_device_name }}"
       description: snapshot of "{{ instance_id }}"
       wait: no
