--- #EC2 Creating New Instance
- hosts: "{{ var_hosts }}"
  remote_user: "{{ var_remote_user }}"
  become: "{{ var_become }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  vars_files:
   - files/vars_local.yml
   - files/awscreds.yml
  tasks:
   -  name: Creating the Instance
      ec2:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        key_name: mysydenykey
        instance_type: t2.micro
        image: ami-6c14310f
        wait: yes
        count: 1
        vpc_subnet_id: subnet-bfd8bdda
        assign_public_ip: yes
        instance_tags:
           Name: "{{ Name }}"
        state: present
