--- #EC2 Remote facts
- hosts: "{{ var_hosts }}"
  remote_user: "{{ var_remote_user }}"
  become: "{{ var_become }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  vars_files:
   - files/vars_local.yml
  tasks:
   -  name: EC2 Remote facts using Name
      ec2_remote_facts:
        region: "{{ aws_region }}"
        filters:
         instance-state-name: running
         "tag:Name": "{{ Name }}"
      register: facts_find
   -  name: Printing the Instance ID
      debug: msg="Instance_ID is {{ facts_find.instances[0].id }}"
   -  name: Printing the Private DNS Details
      debug: msg="Private DNS is {{ facts_find.instances[0].private_dns_name }}"
