--- #EC2 Register Instance from ELB
- hosts: "{{ var_hosts }}"
  remote_user: "{{ var_remote_user }}"
  become: "{{ var_become }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  vars_files:
   - files/vars_local.yml
  tasks:
   -  name: Register Instance from ELB
      ec2_elb:
        region: "{{ aws_region }}"
        ec2_elbs: "{{ my_elb_name }}"
        instance_id: "{{ instance_id }}"
        wait: yes
        state: present
