--- #EC2 Snapshot Creation
- hosts: "{{ var_hosts }}"
  remote_user: "{{ var_remote_user }}"
  become: "{{ var_become }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  vars_files:
   - files/vars_local.yml
   - files/awscreds.yml
  tasks:
   -  name: EC2 Snapshot Creation
      ec2_remote_facts:
        aws_access_key: "{{ aws_id }}"
        aws_secret_key: "{{ aws_key }}"
        region: "{{ aws_region }}"
        filters:
         instance-state-name: running
         "tag:Name": "{{ Name }}"
      register: facts_find
   -  debug: msg="{{ facts_find.instances[0].id }}"
   -  debug: msg="{{ facts_find.instances[0].private_dns_name }}"
