--- #PLAYBOOK FOR PACKAGE UPDATE USING YUM
- hosts: "{{ var_hosts }}"
  user: "{{ var_remote_user }}"
  become: "{{ var_become }}"
  connection: "{{ var_connection }}"
  gather_facts: "{{ var_gather_facts }}"
  vars_files:
         - files/vars_remote.yml
  tasks:
  - name: Update package on Redhat Based System
    when: ansible_os_family == "RedHat"
    yum: name={{ item }} state=latest
    async: 40
    poll: 10
    with_items:
    - httpd
